/*
Name:  Dan Haub
Student ID#:  2315346
Chapman Email:  haub@chapman.edu
Course Number and Section:  CPSC 350-01
Assignment:  2- Game of Life
*/

#ifndef BOARD_H
#define BOARD_H

#include "cell.h"
#include "classic.h"
#include "doughnut.h"
#include "edge_type.h"
#include "mirror.h"
#include "randomizer.h"
#include "game_reader.h"
#include <iostream>

class Board{
    private: 
        //Holds the cell objects used in the simulation
        Cell** generation_; 

        //Holds information on which edge type is being used
        EdgeType *board_edge_type_; 

        //If the user chooses, the simulation will begin with a random board generated by this object
        Randomizer *board_randomizer_; 

        //If the user chooses, the simulation will begin with a board read from a file by this object
        GameReader *file_reader_; 

        //stores the dimensions of the board
        int height_; 
        int width_;

        //stores how many generations have passed since the initial state
        int generation_number_ = 0;
    
    public:
        //Default Constructor
        //10 by 10 grid, randomized (50% alive)
        //classic edge type
        Board();

        //Overloaded Constructor
        //Chosen edge type, chosen randomizer specifications
        Board(EdgeType *board_edge_type, Randomizer *board_randomizer);

        //Overloaded Constructor
        //Chosen edge type, chorsen file reader
        Board(EdgeType *board_edge_type, GameReader *file_reader);

        //Default Destructor
        ~Board();

        //calls EdgeType.Iterate(Cell[][] generation)
        //updates generation_ accodringly
        void Iterate();

        //gives a string representation of the board's generation_
        string ToString();


};

#endif //BOARD_H